### ISSUE TITLE
Not working with "does not extend anything and does not have any code" warning

### ISSUE THREAD

**Issue by auduongtuan** [BoDonkey/rich-text-enhancement#3]
It seems like this extension doesn't work; I've tested in apostrophe v3.63.3 and v4.1.1 following the instructions.
In both cases, it ends with this warning:

```
⚠️
 It looks like you may have made a mistake in your code:
The module rich-text-color does not extend anything and does not have any code.

This usually means that you:

1. Forgot to "extend" another module
2. Configured a module that comes from npm without npm installing it
3. Simply haven't written your "index.js" yet

If you really want a module with no code, set the ignoreNoCodeWarning option
to true for this module.
```

Is this extension still working? Is there anything I need to be aware of when setting up this extension?

**Comment by LeviticusMaximus** [comment]
the solution is that the readme says to add this line to app.js

`bundle: [ '@bodonkey/rich-text-enhancement' ],`

when in fact you need to make **'bundle'** plural, and everything will work fine:

`bundles: [ '@bodonkey/rich-text-enhancement' ],`

**Comment by BoDonkey** [comment]
Thanks! Sorry for the confusion.
