### ISSUE TITLE
readme installation instructions error

### ISSUE THREAD

**Issue by LeviticusMaximus** [BoDonkey/rich-text-enhancement#4]
Great extension, but the instruction to add

`bundle: [ '@bodonkey/rich-text-enhancement' ],`

to app.js is wrong, might be an idea to change the readme to 

`bundles: [ '@bodonkey/rich-text-enhancement' ],`

to help users get it working.

**Comment by BoDonkey** [comment]
Thanks for seeing this and helping out!
